# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "is-pattern-1.resource.prefix" . }}-identity-server-conf
  namespace : {{ .Release.Namespace }}
  {{ if .Values.wso2.deployment.wso2is.config }}

data:
  {{- range $index, $content := .Values.wso2.deployment.wso2is.config }}
  {{ $index }}: |-
  {{ tpl $content $ | indent 4 }}
  {{- end }}

  {{ else }}
data:
  deployment.toml: |-
    # Deployment config for Identity Server deployment
    [server]
    hostname = "{{ .Values.wso2.deployment.wso2is.ingress.identity.hostname }}"
    node_ip = "$env{NODE_IP}"
    base_path = "https://$ref{server.hostname}"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.user]
    {{- if .Values.wso2.deployment.wso2is.customConfig.dataSources.server.enableSSL }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.name }}?autoReconnect=true&amp;sslMode=VERIFY_CA&amp;serverTimezone=UTC&amp;enabledTLSProtocols=TLSv1.2"
    {{- else }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.name }}?autoReconnect=true&amp;useSSL=false&amp;serverTimezone=UTC"
    {{- end }}
    username = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.username | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.password | quote }}
    driver = "com.mysql.cj.jdbc.Driver"

    [realm_manager]
    data_source = "WSO2USER_DB"

    [database.user.pool_options]
    validationQuery = "SELECT 1"

    [transport.https.properties]
    proxyPort="443"

    [database.identity_db]
    {{- if .Values.wso2.deployment.wso2is.customConfig.dataSources.server.enableSSL }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.identity.name }}?autoReconnect=true&amp;sslMode=VERIFY_CA&amp;serverTimezone=UTC&amp;enabledTLSProtocols=TLSv1.2"
    {{- else }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.identity.name }}?autoReconnect=true&amp;useSSL=false&amp;serverTimezone=UTC"
    {{- end }}
    username = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.identity.username | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.identity.password | quote }}
    driver = "com.mysql.cj.jdbc.Driver"

    [database.identity_db.pool_options]
    validationQuery = "SELECT 1"

    [database.shared_db]
    {{- if .Values.wso2.deployment.wso2is.customConfig.dataSources.server.enableSSL }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.name }}?autoReconnect=true&amp;sslMode=VERIFY_CA&amp;serverTimezone=UTC&amp;enabledTLSProtocols=TLSv1.2"
    {{- else }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.name }}?autoReconnect=true&amp;useSSL=false&amp;serverTimezone=UTC"
    {{- end }}
    username = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.username | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.shared.password | quote }}
    driver = "com.mysql.cj.jdbc.Driver"

    [account_recovery.endpoint.auth]
    hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

    [identity.auth_framework.endpoint]
    app_password= "dashboard"

    [database.shared_db.pool_options]
    validationQuery = "SELECT 1"

    [database.bps_database]
    {{- if .Values.wso2.deployment.wso2is.customConfig.dataSources.server.enableSSL }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.bps.name }}?autoReconnect=true&amp;sslMode=VERIFY_CA&amp;serverTimezone=UTC&amp;enabledTLSProtocols=TLSv1.2"
    {{- else }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.bps.name }}?autoReconnect=true&amp;useSSL=false&amp;serverTimezone=UTC"
    {{- end }}
    username = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.bps.username | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.bps.password | quote }}
    driver = "com.mysql.cj.jdbc.Driver"

    [database.bps_database.pool_options]
    validationQuery = "SELECT 1"

    [datasource.WSO2ConsentDS]
    id = "WSO2ConsentDS"
    {{- if .Values.wso2.deployment.wso2is.customConfig.dataSources.server.enableSSL }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.consent.name }}?autoReconnect=true&amp;sslMode=VERIFY_CA&amp;serverTimezone=UTC&amp;enabledTLSProtocols=TLSv1.2"
    {{- else }}
    url = "jdbc:mysql://{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.hostname }}:{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.server.port }}/{{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.consent.name }}?autoReconnect=true&amp;useSSL=false&amp;serverTimezone=UTC"
    {{- end }}
    username = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.consent.username | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.dataSources.databases.consent.password | quote }}
    driver = "com.mysql.cj.jdbc.Driver"
    pool_options.validationQuery="SELECT 1"
    pool_options.maxActive=50
    pool_options.maxWait = 60000 # wait in milliseconds
    pool_options.testOnBorrow = true
    pool_options.jmxEnabled = false
    [authentication.consent]
    data_source="jdbc/WSO2ConsentDS"

    [keystore.primary]
    file_name =  "primary-keystore.jks"
    type =  "JKS"
    alias =  {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.primary.alias | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.primary.password | quote }}
    key_password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.primary.password | quote }}

    [keystore.tls]
    file_name =  "secondary-keystore.jks"
    type =  "JKS"
    alias =  {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.secondary.alias | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.secondary.password | quote }}
    key_password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.secondary.password | quote }}

    [keystore.internal]
    file_name =  "internal-keystore.jks"
    type =  "JKS"
    alias =  {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.internal.alias | quote }}
    password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.internal.password | quote }}
    key_password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.keyStores.internal.password | quote }}

    [truststore]
    file_name = "client-truststore.jks"
    type = "JKS"
    password = {{ .Values.wso2.deployment.wso2is.customConfig.cryptography.trustStorePassword | quote }}

    [clustering]
    membership_scheme = "kubernetes"
    domain = "wso2.carbon.domain"
    properties.membershipSchemeClassName = "org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme"
    properties.KUBERNETES_NAMESPACE = "{{ .Release.Namespace }}"
    properties.KUBERNETES_SERVICES = "{{ template "is-pattern-1.resource.prefix" . }}-identity-service"
    properties.KUBERNETES_MASTER_SKIP_SSL_VERIFICATION = "true"
    properties.USE_DNS = "false"

    [carbon_health_check]
    enable= true
    health_checker.super_tenant_health_checker.properties.'monitored.user.stores' = "primary"
    health_checker.data_source_health_checker.properties.'monitored.datasources' = "jdbc/WSO2CarbonDB,jdbc/WSO2USER_DB,jdbc/SHARED_DB,jdbc/WSO2IdentityDB,jdbc/WSO2ConsentDS"

    [[event_listener]]
    id = "token_revocation"
    type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
    name = "org.wso2.is.notification.ApimOauthEventInterceptor"
    order = 1

    [[resource.access_control]]
    context = "(.)/keymanager-operations/user-info/claims(.)"
    secure = true
    http_method = "GET"
    permissions = "/permission/admin/manage/identity/usermgt/list"
    scopes = "internal_user_mgt_list"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/user-info/claims/generate"
    secure = true
    http_method = "POST"
    permissions = "/permission/admin/manage/identity/usermgt/list"
    scopes = "internal_user_mgt_list"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register"
    secure = true
    http_method = "POST"
    permissions = "/permission/admin/manage/identity/applicationmgt/create"
    scopes = "internal_application_mgt_create"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register(.*)"
    secure = true
    http_method = "GET"
    permissions = "/permission/admin/manage/identity/applicationmgt/view"
    scopes = "internal_application_mgt_view"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register(.*)"
    secure = true
    http_method = "DELETE"
    permissions = "/permission/admin/manage/identity/applicationmgt/delete"
    scopes = "internal_application_mgt_delete"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register(.*)"
    secure = true
    http_method = "PUT"
    permissions = "/permission/admin/manage/identity/applicationmgt/update"
    scopes = "internal_application_mgt_update"

    [[resource.access_control]]
    context = "(.)/keymanager-operations/dcr/register(.)"
    secure = true
    http_method = "POST"
    permissions = "/permission/admin/manage/identity/applicationmgt/update"
    scopes = "internal_application_mgt_update"

    [tenant_context.rewrite]
    custom_webapps = ["/keymanager-operations/"]

    [event_listener.properties]
    notification_endpoint = "https://wso2am-pattern-3-am-cp-service:9443/internal/data/v1/notify"
    username = "${admin.username}"
    password = "${admin.password}"
    'header.X-WSO2-KEY-MANAGER' = "WSO2-IS"

    [config_data]
    path = "/_system/is_as_km/config"

    {{ if .Values.wso2.monitoring.enabled }}
    [monitoring.jmx]
    rmi_server_start = true
    {{- end }}
  {{- end }}
